
package com.se.pumptesting.models;
// Generated Mar 2, 2019 12:48:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tbl08InstrumentMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_08_InstrumentMaster", schema = "dbo", catalog = "PumpTesting_SE", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "NAME", "CLIENT_ID" }), @UniqueConstraint(columnNames = { "CLIENT_ID", "PARAMETER" }) })
public class Tbl08InstrumentMaster implements java.io.Serializable {

	private int id;

	private String name;

	private String parameter;

	private String columnName;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String clientId;

	public Tbl08InstrumentMaster() {
	}

	public Tbl08InstrumentMaster(int id) {
		this.id = id;
	}

	public Tbl08InstrumentMaster(int id, String name, String parameter, String columnName, String clientId) {
		this.id = id;
		this.name = name;
		this.parameter = parameter;
		this.columnName = columnName;
		this.clientId = clientId;
	}

	public Tbl08InstrumentMaster(int id, String name, String parameter, String columnName, String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, String clientId) {
		this.id = id;
		this.name = name;
		this.parameter = parameter;
		this.columnName = columnName;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.clientId = clientId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	@Column(name = "PARAMETER", nullable = false, length = 50)
	public String getParameter() {

		return this.parameter;
	}

	public void setParameter(String parameter) {

		this.parameter = parameter;
	}

	@Column(name = "COLUMN_NAME", nullable = false, length = 50)
	public String getColumnName() {

		return this.columnName;
	}

	public void setColumnName(String columnName) {

		this.columnName = columnName;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_BY", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CLIENT_ID", nullable = false, length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

}
