
package com.se.pumptesting.models;
// Generated Dec 10, 2018 7:08:53 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl02Company generated by hbm2java
 */
@Entity
@Table(name = "tbl_00_Client", schema = "dbo", catalog = "PumpTesting_SE", uniqueConstraints = @UniqueConstraint(columnNames = "COMPANY_NAME"))
@FilterDef(name = "ClientIdCheck", parameters = { @ParamDef(name = "clientIdParam", type = "java.lang.String") })
@Filter(name = "ClientIdCheck", condition = ":clientIdParam= CLIENT_ID ")
public class Tbl00Client implements java.io.Serializable {

	private int id;

	private String companyName;

	private String address1;

	private String city;

	private String state;

	private String country;

	private String postalCode;

	private String email;

	private String website;

	private String logoName;

	private String currency;

	private String mobileNo;

	private String contactPhone;

	private String tinNo;

	private String panNo;

	private String clientId;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String gstStateCode;

	private String gstNumber;

	private String corporateIdentityNumber;

	private String arnNumber;

	private String iecCode;

	private String companyShort;

	public Tbl00Client() {
	}

	public Tbl00Client(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "COMPANY_NAME", unique = true, length = 100)
	public String getCompanyName() {

		return this.companyName;
	}

	public void setCompanyName(String companyName) {

		this.companyName = companyName;
	}

	@Column(name = "ADDRESS1")
	public String getAddress1() {

		return this.address1;
	}

	public void setAddress1(String address1) {

		this.address1 = address1;
	}

	@Column(name = "CITY", length = 50)
	public String getCity() {

		return this.city;
	}

	public void setCity(String city) {

		this.city = city;
	}

	@Column(name = "STATE", length = 50)
	public String getState() {

		return this.state;
	}

	public void setState(String state) {

		this.state = state;
	}

	@Column(name = "COUNTRY", length = 50)
	public String getCountry() {

		return this.country;
	}

	public void setCountry(String country) {

		this.country = country;
	}

	@Column(name = "POSTAL_CODE", length = 50)
	public String getPostalCode() {

		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {

		this.postalCode = postalCode;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {

		return this.email;
	}

	public void setEmail(String email) {

		this.email = email;
	}

	@Column(name = "WEBSITE", length = 50)
	public String getWebsite() {

		return this.website;
	}

	public void setWebsite(String website) {

		this.website = website;
	}

	@Column(name = "LOGO_NAME")
	public String getLogoName() {

		return this.logoName;
	}

	public void setLogoName(String logoName) {

		this.logoName = logoName;
	}

	@Column(name = "CURRENCY", length = 50)
	public String getCurrency() {

		return this.currency;
	}

	public void setCurrency(String currency) {

		this.currency = currency;
	}

	@Column(name = "MOBILE_NO", length = 50)
	public String getMobileNo() {

		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {

		this.mobileNo = mobileNo;
	}

	@Column(name = "CONTACT_PHONE", length = 50)
	public String getContactPhone() {

		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {

		this.contactPhone = contactPhone;
	}

	@Column(name = "TIN_NO", length = 50)
	public String getTinNo() {

		return this.tinNo;
	}

	public void setTinNo(String tinNo) {

		this.tinNo = tinNo;
	}

	@Column(name = "PAN_NO", length = 50)
	public String getPanNo() {

		return this.panNo;
	}

	public void setPanNo(String panNo) {

		this.panNo = panNo;
	}

	@Column(name = "CLIENT_ID", nullable = false, length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_BY", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "GST_STATE_CODE", length = 5)
	public String getGstStateCode() {

		return this.gstStateCode;
	}

	public void setGstStateCode(String gstStateCode) {

		this.gstStateCode = gstStateCode;
	}

	@Column(name = "GST_NUMBER", length = 20)
	public String getGstNumber() {

		return this.gstNumber;
	}

	public void setGstNumber(String gstNumber) {

		this.gstNumber = gstNumber;
	}

	@Column(name = "CORPORATE_IDENTITY_NUMBER", length = 50)
	public String getCorporateIdentityNumber() {

		return this.corporateIdentityNumber;
	}

	public void setCorporateIdentityNumber(String corporateIdentityNumber) {

		this.corporateIdentityNumber = corporateIdentityNumber;
	}

	@Column(name = "ARN_NUMBER", length = 50)
	public String getArnNumber() {

		return this.arnNumber;
	}

	public void setArnNumber(String arnNumber) {

		this.arnNumber = arnNumber;
	}

	@Column(name = "IEC_CODE", length = 100)
	public String getIecCode() {

		return this.iecCode;
	}

	public void setIecCode(String iecCode) {

		this.iecCode = iecCode;
	}

	@Column(name = "COMPANY_SHORT", length = 50)
	public String getCompanyShort() {

		return this.companyShort;
	}

	public void setCompanyShort(String companyShort) {

		this.companyShort = companyShort;
	}

}
