
package com.se.pumptesting.models;
// Generated Dec 31, 2018 2:03:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbl03TestbedMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_03_TestbedMaster", schema = "dbo", catalog = "PumpTesting_SE")
/* @Filter(name = "ClientIdCheck", condition = ":clientIdParam= CLIENT_ID ") */
public class Tbl03TestbedMaster implements java.io.Serializable {

	private int id;

	private String testbedNo;

	private String desciption;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String clientId;

	private Set<Tbl04TestingMaster> tbl04TestingMasters = new HashSet<Tbl04TestingMaster>(0);

	public Tbl03TestbedMaster() {
	}

	public Tbl03TestbedMaster(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "TESTBED_NO", nullable = false, length = 50)
	public String getTestbedNo() {

		return this.testbedNo;
	}

	public void setTestbedNo(String testbedNo) {

		this.testbedNo = testbedNo;
	}

	@Column(name = "DESCIPTION")
	public String getDesciption() {

		return this.desciption;
	}

	public void setDesciption(String desciption) {

		this.desciption = desciption;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_BY", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CLIENT_ID", nullable = false, length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl03TestbedMaster")
	public Set<Tbl04TestingMaster> getTbl04TestingMasters() {

		return this.tbl04TestingMasters;
	}

	public void setTbl04TestingMasters(Set<Tbl04TestingMaster> tbl04TestingMasters) {

		this.tbl04TestingMasters = tbl04TestingMasters;
	}

}
