
package com.se.pumptesting.models;
// default package

// Generated Mar 17, 2019 11:50:20 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbl00MotorMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_00_MotorMaster", schema = "dbo", catalog = "PumpTesting_SE")
public class Tbl00MotorMaster implements java.io.Serializable {

	private int id;

	private String motorNo;

	private String make;

	private int phase;

	private Double power;

	private Double powerHp;

	private Double speed;

	private Double efficiency;

	private String frame;

	private Double voltage;

	private Double current;

	private Double frequency;

	private Integer pole;

	private String efficiencyClass;

	private String specification;

	private Double resistanceTemprature;

	private Double resistanceR;

	private Double resistanceY;

	private Double resistanceB;

	private Double noloadPower;

	private Double noloadCurrent;

	private String connectionType;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String clientId;

	private Set<Tbl04TestingMaster> tbl04TestingMasters = new HashSet<Tbl04TestingMaster>(0);

	private Set<Tbl00MotorNoLoadDetails> tbl00MotorNoLoadDetailses = new HashSet<Tbl00MotorNoLoadDetails>(0);

	public Tbl00MotorMaster() {
	}

	public Tbl00MotorMaster(int id) {
		this.id = id;

	}

	public Tbl00MotorMaster(int id, String motorNo, int phase) {
		this.id = id;
		this.motorNo = motorNo;
		this.phase = phase;
	}

	public Tbl00MotorMaster(int id, String motorNo, String make, int phase, Double power, Double speed, Double efficiency, String frame,
			Double voltage, Double current, Double frequency, Integer pole, String efficiencyClass, String specification, Double resistanceR,
			Double resistanceY, Double resistanceB, Double noloadPower, Double noloadCurrent, String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, String clientId, Set<Tbl04TestingMaster> tbl04TestingMasters, Set<Tbl00MotorNoLoadDetails> tbl00MotorNoLoadDetailses) {
		this.id = id;
		this.motorNo = motorNo;
		this.make = make;
		this.phase = phase;
		this.power = power;
		this.speed = speed;
		this.efficiency = efficiency;
		this.frame = frame;
		this.voltage = voltage;
		this.current = current;
		this.frequency = frequency;
		this.pole = pole;
		this.efficiencyClass = efficiencyClass;
		this.specification = specification;
		this.resistanceR = resistanceR;
		this.resistanceY = resistanceY;
		this.resistanceB = resistanceB;
		this.noloadPower = noloadPower;
		this.noloadCurrent = noloadCurrent;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.clientId = clientId;
		this.tbl04TestingMasters = tbl04TestingMasters;
		this.tbl00MotorNoLoadDetailses = tbl00MotorNoLoadDetailses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "MOTOR_NO", nullable = false, length = 50)
	public String getMotorNo() {

		return this.motorNo;
	}

	public void setMotorNo(String motorNo) {

		this.motorNo = motorNo;
	}

	@Column(name = "MAKE")
	public String getMake() {

		return this.make;
	}

	public void setMake(String make) {

		this.make = make;
	}

	@Column(name = "PHASE", nullable = false)
	public int getPhase() {

		return this.phase;
	}

	public void setPhase(int phase) {

		this.phase = phase;
	}

	@Column(name = "POWER", precision = 53, scale = 0)
	public Double getPower() {

		return this.power;
	}

	public void setPower(Double power) {

		this.power = power;
	}

	@Column(name = "SPEED", precision = 53, scale = 0)
	public Double getSpeed() {

		return this.speed;
	}

	public void setSpeed(Double speed) {

		this.speed = speed;
	}

	@Column(name = "EFFICIENCY", precision = 53, scale = 0)
	public Double getEfficiency() {

		return this.efficiency;
	}

	public void setEfficiency(Double efficiency) {

		this.efficiency = efficiency;
	}

	@Column(name = "FRAME", length = 50)
	public String getFrame() {

		return this.frame;
	}

	public void setFrame(String frame) {

		this.frame = frame;
	}

	@Column(name = "VOLTAGE", precision = 53, scale = 0)
	public Double getVoltage() {

		return this.voltage;
	}

	public void setVoltage(Double voltage) {

		this.voltage = voltage;
	}

	@Column(name = "CURRENT_", precision = 53, scale = 0)
	public Double getCurrent() {

		return this.current;
	}

	public void setCurrent(Double current) {

		this.current = current;
	}

	@Column(name = "FREQUENCY", precision = 53, scale = 0)
	public Double getFrequency() {

		return this.frequency;
	}

	public void setFrequency(Double frequency) {

		this.frequency = frequency;
	}

	@Column(name = "POLE")
	public Integer getPole() {

		return this.pole;
	}

	public void setPole(Integer pole) {

		this.pole = pole;
	}

	@Column(name = "EFFICIENCY_CLASS", length = 50)
	public String getEfficiencyClass() {

		return this.efficiencyClass;
	}

	public void setEfficiencyClass(String efficiencyClass) {

		this.efficiencyClass = efficiencyClass;
	}

	@Column(name = "SPECIFICATION", length = 50)
	public String getSpecification() {

		return this.specification;
	}

	public void setSpecification(String specification) {

		this.specification = specification;
	}

	@Column(name = "RESISTANCE_R", precision = 53, scale = 0)
	public Double getResistanceR() {

		return this.resistanceR;
	}

	public void setResistanceR(Double resistanceR) {

		this.resistanceR = resistanceR;
	}

	@Column(name = "RESISTANCE_Y", precision = 53, scale = 0)
	public Double getResistanceY() {

		return this.resistanceY;
	}

	public void setResistanceY(Double resistanceY) {

		this.resistanceY = resistanceY;
	}

	@Column(name = "RESISTANCE_B", precision = 53, scale = 0)
	public Double getResistanceB() {

		return this.resistanceB;
	}

	public void setResistanceB(Double resistanceB) {

		this.resistanceB = resistanceB;
	}

	@Column(name = "NOLOAD_POWER", precision = 53, scale = 0)
	public Double getNoloadPower() {

		return this.noloadPower;
	}

	public void setNoloadPower(Double noloadPower) {

		this.noloadPower = noloadPower;
	}

	@Column(name = "NOLOAD_CURRENT", precision = 53, scale = 0)
	public Double getNoloadCurrent() {

		return this.noloadCurrent;
	}

	public void setNoloadCurrent(Double noloadCurrent) {

		this.noloadCurrent = noloadCurrent;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_BY", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CLIENT_ID", length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl00MotorMaster")
	public Set<Tbl04TestingMaster> getTbl04TestingMasters() {

		return this.tbl04TestingMasters;
	}

	public void setTbl04TestingMasters(Set<Tbl04TestingMaster> tbl04TestingMasters) {

		this.tbl04TestingMasters = tbl04TestingMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl00MotorMaster")
	public Set<Tbl00MotorNoLoadDetails> getTbl00MotorNoLoadDetailses() {

		return this.tbl00MotorNoLoadDetailses;
	}

	public void setTbl00MotorNoLoadDetailses(Set<Tbl00MotorNoLoadDetails> tbl00MotorNoLoadDetailses) {

		this.tbl00MotorNoLoadDetailses = tbl00MotorNoLoadDetailses;
	}

	@Column(name = "RESISTANCE_TEMPERATURE", length = 50)
	public Double getResistanceTemprature() {

		return resistanceTemprature;
	}

	public void setResistanceTemprature(Double resistanceTemprature) {

		this.resistanceTemprature = resistanceTemprature;
	}

	@Column(name = "POWER_HP", length = 50)
	public Double getPowerHp() {

		return powerHp;
	}

	public void setPowerHp(Double powerHp) {

		this.powerHp = powerHp;
	}

	@Column(name = "CONNECTION_TYPE", length = 50)
	public String getConnectionType() {

		return connectionType;
	}

	public void setConnectionType(String connectionType) {

		this.connectionType = connectionType;
	}

}
