
// Generated Mar 2, 2019 12:48:35 PM by Hibernate Tools 4.3.1.Final

package com.se.pumptesting.models;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbl05TestingData generated by hbm2java
 */
@Entity
@Table(name = "tbl_05_TestingData", schema = "dbo", catalog = "PumpTesting_SE")
public class Tbl05TestingData implements java.io.Serializable {

	private int id;

	private Tbl04TestingMaster tbl04TestingMaster;

	private Double pressureSuction;

	private Double pressureDischarge;

	private Double distanceBetwnGauge;

	private Double velocityheadSuction;

	private Double velocityheadDischarge;

	private Double velocityheadTotal;

	private Double totalHead;

	private Double current_;

	private Double voltage;

	private Double powerfactor;

	private Double flow;

	private Double speed;

	private Double frequency;

	private Double motorPower;

	private Double motorEff;

	private Double pumpInput;

	private Double headDc;

	private Double flowDc;

	private Double powerDc;

	private Double efficiencyDc;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String clientId;

	public Tbl05TestingData() {
	}

	public Tbl05TestingData(int id, Tbl04TestingMaster tbl04TestingMaster) {
		this.id = id;
		this.tbl04TestingMaster = tbl04TestingMaster;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TESTING_MASTER_ID", nullable = false)
	public Tbl04TestingMaster getTbl04TestingMaster() {

		return this.tbl04TestingMaster;
	}

	public void setTbl04TestingMaster(Tbl04TestingMaster tbl04TestingMaster) {

		this.tbl04TestingMaster = tbl04TestingMaster;
	}

	@Column(name = "PRESSURE_SUCTION", precision = 53, scale = 0)
	public Double getPressureSuction() {

		return this.pressureSuction;
	}

	public void setPressureSuction(Double pressureSuction) {

		this.pressureSuction = pressureSuction;
	}

	@Column(name = "PRESSURE_DISCHARGE", precision = 53, scale = 0)
	public Double getPressureDischarge() {

		return this.pressureDischarge;
	}

	public void setPressureDischarge(Double pressureDischarge) {

		this.pressureDischarge = pressureDischarge;
	}

	@Column(name = "DISTANCE_BETWN_GAUGE", precision = 53, scale = 0)
	public Double getDistanceBetwnGauge() {

		return this.distanceBetwnGauge;
	}

	public void setDistanceBetwnGauge(Double distanceBetwnGauge) {

		this.distanceBetwnGauge = distanceBetwnGauge;
	}

	@Column(name = "VELOCITYHEAD_SUCTION", precision = 53, scale = 0)
	public Double getVelocityheadSuction() {

		return this.velocityheadSuction;
	}

	public void setVelocityheadSuction(Double velocityheadSuction) {

		this.velocityheadSuction = velocityheadSuction;
	}

	@Column(name = "VELOCITYHEAD_DISCHARGE", precision = 53, scale = 0)
	public Double getVelocityheadDischarge() {

		return this.velocityheadDischarge;
	}

	public void setVelocityheadDischarge(Double velocityheadDischarge) {

		this.velocityheadDischarge = velocityheadDischarge;
	}

	@Column(name = "VELOCITYHEAD_TOTAL", precision = 53, scale = 0)
	public Double getVelocityheadTotal() {

		return this.velocityheadTotal;
	}

	public void setVelocityheadTotal(Double velocityheadTotal) {

		this.velocityheadTotal = velocityheadTotal;
	}

	@Column(name = "TOTAL_HEAD", precision = 53, scale = 0)
	public Double getTotalHead() {

		return this.totalHead;
	}

	public void setTotalHead(Double totalHead) {

		this.totalHead = totalHead;
	}

	@Column(name = "CURRENT_", precision = 53, scale = 0)
	public Double getCurrent_() {

		return current_;
	}

	public void setCurrent_(Double current_) {

		this.current_ = current_;
	}

	@Column(name = "VOLTAGE", precision = 53, scale = 0)
	public Double getVoltage() {

		return this.voltage;
	}

	public void setVoltage(Double voltage) {

		this.voltage = voltage;
	}

	@Column(name = "POWERFACTOR", precision = 53, scale = 0)
	public Double getPowerfactor() {

		return this.powerfactor;
	}

	public void setPowerfactor(Double powerfactor) {

		this.powerfactor = powerfactor;
	}

	@Column(name = "FLOW", precision = 53, scale = 0)
	public Double getFlow() {

		return this.flow;
	}

	public void setFlow(Double flow) {

		this.flow = flow;
	}

	@Column(name = "SPEED", precision = 53, scale = 0)
	public Double getSpeed() {

		return this.speed;
	}

	public void setSpeed(Double speed) {

		this.speed = speed;
	}

	@Column(name = "FREQUENCY", precision = 53, scale = 0)
	public Double getFrequency() {

		return this.frequency;
	}

	public void setFrequency(Double frequency) {

		this.frequency = frequency;
	}

	@Column(name = "MOTOR_POWER", precision = 53, scale = 0)
	public Double getMotorPower() {

		return this.motorPower;
	}

	public void setMotorPower(Double motorPower) {

		this.motorPower = motorPower;
	}

	@Column(name = "MOTOR_EFF", precision = 53, scale = 0)
	public Double getMotorEff() {

		return this.motorEff;
	}

	public void setMotorEff(Double motorEff) {

		this.motorEff = motorEff;
	}

	@Column(name = "PUMP_INPUT", precision = 53, scale = 0)
	public Double getPumpInput() {

		return this.pumpInput;
	}

	public void setPumpInput(Double pumpInput) {

		this.pumpInput = pumpInput;
	}

	@Column(name = "HEAD_DC", precision = 53, scale = 0)
	public Double getHeadDc() {

		return this.headDc;
	}

	public void setHeadDc(Double headDc) {

		this.headDc = headDc;
	}

	@Column(name = "FLOW_DC", precision = 53, scale = 0)
	public Double getFlowDc() {

		return this.flowDc;
	}

	public void setFlowDc(Double flowDc) {

		this.flowDc = flowDc;
	}

	@Column(name = "POWER_DC", precision = 53, scale = 0)
	public Double getPowerDc() {

		return this.powerDc;
	}

	public void setPowerDc(Double powerDc) {

		this.powerDc = powerDc;
	}

	@Column(name = "EFFICIENCY_DC", precision = 53, scale = 0)
	public Double getEfficiencyDc() {

		return this.efficiencyDc;
	}

	public void setEfficiencyDc(Double efficiencyDc) {

		this.efficiencyDc = efficiencyDc;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_BY", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "CLIENT_ID", length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

}
